---
apiVersion: v1
kind: ConfigMap
metadata:
  name: web-conf
data:
  nginx.conf: |
    # nginx 配置
    user  root;
    worker_processes auto;
    
    #error_log  logs/error.log;
    #error_log  logs/error.log  notice;
    #error_log  logs/error.log  info;
    
    #pid        logs/nginx.pid;
    
    
    events {
        worker_connections  1024;
    }
    
    
    http {
        include       mime.types;
        default_type  application/octet-stream;
    
        #log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
        #                  '$status $body_bytes_sent "$http_referer" '
        #                  '"$http_user_agent" "$http_x_forwarded_for"';
    
        #access_log  logs/access.log  main;
    
        sendfile        on;
        #tcp_nopush     on;
    
        #keepalive_timeout  0;
        server {
    	listen       8193;
            root  /usr/java/beiyun-front/dist;
            index index.html;
            autoindex on;
        }
    
        server {
            listen       8090;
            root  /usr/java/minio-front;
            index index.html;
            autoindex on;
        }
     
        upstream backend_tenant {
            server 192.168.31.191:8088;
        }
    
        upstream backend_monitor {
            server 192.168.31.191:8082;
        }
    
        upstream backend_volumn {
            server 192.168.31.191:8189;
        }
    
        upstream beiyun_front {
            server 192.168.31.191:8193;
        }
    
        upstream qos_ser {
            server 192.168.31.191:8888;
        }
    
        upstream swirl_front {
            server 192.168.31.191:8089;
        }
    
        upstream minio_front {
            server 192.168.31.191:8090;
        }
    
        upstream minio_service{
            server 161.189.150.27:9306;
        }
    
        server {
            listen       8192;
    
            location ~ /minio/admin/
            {
                proxy_pass http://minio_service;
                proxy_read_timeout 300;
                proxy_connect_timeout 300;
                proxy_redirect     off;
    
                proxy_set_header   X-Forwarded-Proto $scheme;
                proxy_set_header   Host              $http_host;
                proxy_set_header   X-Real-IP         $remote_addr;
            }
    
            location ~ /minio/
            {
                proxy_pass http://minio_front;
                proxy_read_timeout 300;
                proxy_connect_timeout 300;
                proxy_redirect     off;
    
                proxy_set_header   X-Forwarded-Proto $scheme;
                proxy_set_header   Host              $http_host;
                proxy_set_header   X-Real-IP         $remote_addr;
            }
    
            location ~ /swirl/
            {
                proxy_pass http://swirl_front;
                proxy_read_timeout 300;
                proxy_connect_timeout 300;
                proxy_redirect     off;
    
                proxy_set_header   X-Forwarded-Proto $scheme;
                proxy_set_header   Host              $http_host;
                proxy_set_header   X-Real-IP         $remote_addr;
            }
    
            location ~ /tenant/
            {
                proxy_pass http://backend_tenant;
                proxy_read_timeout 300;
                proxy_connect_timeout 300;
                proxy_redirect     off;
    
                proxy_set_header   X-Forwarded-Proto $scheme;
                proxy_set_header   Host              $http_host;
                proxy_set_header   X-Real-IP         $remote_addr;
            }
            location ~ /fileservice/
            {
                proxy_pass http://backend_tenant;
                proxy_read_timeout 300;
                proxy_connect_timeout 300;
                proxy_redirect     off;
    
                proxy_set_header   X-Forwarded-Proto $scheme;
                proxy_set_header   Host              $http_host;
                proxy_set_header   X-Real-IP         $remote_addr;
            }
    
            location ~ /user/
            {
                proxy_pass http://backend_tenant;
                proxy_read_timeout 300;
                proxy_connect_timeout 300;
                proxy_redirect     off;
    
                proxy_set_header   X-Forwarded-Proto $scheme;
                proxy_set_header   Host              $http_host;
                proxy_set_header   X-Real-IP         $remote_addr;
            }
            location ~ /platform/
            {
                proxy_pass http://backend_tenant;
                proxy_read_timeout 300;
                proxy_connect_timeout 300;
                proxy_redirect     off;
    
                proxy_set_header   X-Forwarded-Proto $scheme;
                proxy_set_header   Host              $http_host;
                proxy_set_header   X-Real-IP         $remote_addr;
            }
            location ~ /refresh_session
            {
                proxy_pass http://backend_tenant;
                proxy_read_timeout 300;
                proxy_connect_timeout 300;
                proxy_redirect     off;
    
                proxy_set_header   X-Forwarded-Proto $scheme;
                proxy_set_header   Host              $http_host;
                proxy_set_header   X-Real-IP         $remote_addr;
            }    
            location ~ /volume/
            {
                proxy_pass http://backend_volumn;
                proxy_read_timeout 300;
                proxy_connect_timeout 300;
                proxy_redirect     off;
    
                proxy_set_header   X-Forwarded-Proto $scheme;
                proxy_set_header   Host              $http_host;
                proxy_set_header   X-Real-IP         $remote_addr;
            }
            location ~ /replica/
            {
                proxy_pass http://backend_volumn;
                proxy_read_timeout 300;
                proxy_connect_timeout 300;
                proxy_redirect     off;
    
                proxy_set_header   X-Forwarded-Proto $scheme;
                proxy_set_header   Host              $http_host;
                proxy_set_header   X-Real-IP         $remote_addr;
            }
            location ~ /volumepolicy/
            {
                proxy_pass http://backend_volumn;
                proxy_read_timeout 300;
                proxy_connect_timeout 300;
                proxy_redirect     off;
    
                proxy_set_header   X-Forwarded-Proto $scheme;
                proxy_set_header   Host              $http_host;
                proxy_set_header   X-Real-IP         $remote_addr;
            }
            location ~ /snapshot/
            {
                proxy_pass http://backend_volumn;
                proxy_read_timeout 300;
                proxy_connect_timeout 300;
                proxy_redirect     off;
    
                proxy_set_header   X-Forwarded-Proto $scheme;
                proxy_set_header   Host              $http_host;
                proxy_set_header   X-Real-IP         $remote_addr;
            }
            
            location ~ /statistics/
            {
                proxy_pass http://backend_monitor;
                proxy_read_timeout 300;
                proxy_connect_timeout 300;
                proxy_redirect     off;
    
                proxy_set_header   X-Forwarded-Proto $scheme;
                proxy_set_header   Host              $http_host;
                proxy_set_header   X-Real-IP         $remote_addr;
            }
            location ~ /monitor/
            {
                proxy_pass http://backend_monitor;
                proxy_read_timeout 300;
                proxy_connect_timeout 300;
                proxy_redirect     off;
    
                proxy_set_header   X-Forwarded-Proto $scheme;
                proxy_set_header   Host              $http_host;
                proxy_set_header   X-Real-IP         $remote_addr;
            }
            location ~ /maintain/
            {
                proxy_pass http://backend_monitor;
                proxy_read_timeout 300;
                proxy_connect_timeout 300;
                proxy_redirect     off;
    
                proxy_set_header   X-Forwarded-Proto $scheme;
                proxy_set_header   Host              $http_host;
                proxy_set_header   X-Real-IP         $remote_addr;
            }
     
             location ~ /fault/
            {
                proxy_pass http://backend_tenant;
                proxy_read_timeout 300;
                proxy_connect_timeout 300;
                proxy_redirect     off;
    
                proxy_set_header   X-Forwarded-Proto $scheme;
                proxy_set_header   Host              $http_host;
                proxy_set_header   X-Real-IP         $remote_addr;
            }
            location ~ /qos/
            {
                proxy_pass http://qos_ser;
                proxy_read_timeout 300;
                proxy_connect_timeout 300;
                proxy_redirect     off;
    
                proxy_set_header   X-Forwarded-Proto $scheme;
                proxy_set_header   Host              $http_host;
                proxy_set_header   X-Real-IP         $remote_addr;
            }
             location ~ /es/
            {
                proxy_pass http://backend_monitor;
                proxy_read_timeout 300;
                proxy_connect_timeout 300;
                proxy_redirect     off;
    
                proxy_set_header   X-Forwarded-Proto $scheme;
                proxy_set_header   Host              $http_host;
                proxy_set_header   X-Real-IP         $remote_addr;
            }
             location ~ /ldap/
            {
                proxy_pass http://backend_tenant;
                proxy_read_timeout 300;
                proxy_connect_timeout 300;
                proxy_redirect     off;
    
                proxy_set_header   X-Forwarded-Proto $scheme;
                proxy_set_header   Host              $http_host;
                proxy_set_header   X-Real-IP         $remote_addr;
            }
             location ~ /dlp/
            {
                proxy_pass http://backend_tenant;
                proxy_read_timeout 300;
                proxy_connect_timeout 300;
                proxy_redirect     off;
    
                proxy_set_header   X-Forwarded-Proto $scheme;
                proxy_set_header   Host              $http_host;
                proxy_set_header   X-Real-IP         $remote_addr;
            }
            location /
            {
                proxy_pass http://beiyun_front;
                proxy_read_timeout 300;
                proxy_connect_timeout 300;
                proxy_redirect     off;
    
                proxy_set_header   X-Forwarded-Proto $scheme;
                proxy_set_header   Host              $http_host;
                proxy_set_header   X-Real-IP         $remote_addr;   
            }
        }
    
    
        # another virtual host using mix of IP-, name-, and port-based configuration
        #
        #server {
        #    listen       8000;
        #    listen       somename:8080;
        #    server_name  somename  alias  another.alias;
    
        #    location / {
        #        root   html;
        #        index  index.html index.htm;
        #    }
        #}
    
        # HTTPS server
        #
        #server {
        #    listen       443 ssl;
        #    server_name  localhost;
    
        #    ssl_certificate      cert.pem;
        #    ssl_certificate_key  cert.key;
    
        #    ssl_session_cache    shared:SSL:1m;
        #    ssl_session_timeout  5m;
    
        #    ssl_ciphers  HIGH:!aNULL:!MD5;
        #    ssl_prefer_server_ciphers  on;
    
        #    location / {
        #        root   html;
        #        index  index.html index.htm;
        #    }
        #}
    
    }

---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  type: NodePort
  ports:
    - name: web
      protocol: TCP
      port: 8192
      nodePort: 8192
      targetPort: 8192
  selector:
    app: nginx
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web
spec:
  serviceName: "nginx"
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: node1.huoyin.com:5000/amd64/amd64-nginx:1.14.0
        ports:
        - containerPort: 8192
          name: web
        volumeMounts:
        - name: www
          mountPath: /usr/java/beiyun-front/dist
        - name: nginx-conf
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
      volumes:
        - name: www
          hostPath:
            path: /usr/java/beiyun-front/dist
        - name: nginx-conf
          configMap:
            name: web-conf
            items:
              - key: nginx.conf
                path: nginx.conf
