---
apiVersion: v1
kind: Secret
metadata:
  name: aliyun
  namespace: default
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJyZWdpc3RyeS5jbi1iZWlqaW5nLmFsaXl1bmNzLmNvbSI6IHsKCQkJImF1dGgiOiAiZUdsaGJtZHFhV1U0TVRoQU1UWXpMbU52YlRwamRIbHphSFJrYkVBNE1UZz0iCgkJfQoJfSwKCSJIdHRwSGVhZGVycyI6IHsKCQkiVXNlci1BZ2VudCI6ICJEb2NrZXItQ2xpZW50LzE5LjAzLjkgKGxpbnV4KSIKCX0KfQ==
type: kubernetes.io/dockerconfigjson
