---
apiVersion: v1
kind: ConfigMap
metadata:
  name: xtreemfs-dir-conf
data:
  dirconfig.properties: |
    # xtreemfs dir 配置
    listen.port = 32638
    http_port = 30638
    listen.address = 0.0.0.0
    ssl.enabled = false
    ssl.service_creds = /etc/xos/xtreemfs/truststore/certs/dir.p12
    ssl.service_creds.pw = 12344321
    ssl.service_creds.container = pkcs12
    ssl.trusted_certs = /etc/xos/xtreemfs/truststore/certs/trusted.jks
    ssl.trusted_certs.pw = 12344321
    ssl.trusted_certs.container = jks
    policy_dir = /etc/xos/xtreemfs/policies
    babudb.debug.level = 4
    babudb.baseDir = /var/lib/xtreemfs/dir/database
    babudb.logDir = /var/lib/xtreemfs/dir/db-log
    babudb.sync = FDATASYNC
    babudb.worker.maxQueueLength = 250
    babudb.worker.numThreads = 0
    babudb.maxLogfileSize = 16777216
    babudb.checkInterval = 300
    babudb.pseudoSyncWait = 200
    babudb.plugin.0 = /etc/xos/xtreemfs/server-repl-plugin/dir.properties
  dir.properties: |
    babudb.repl.participant.0 = xtreemfs-dir-0.xtreemfs-dir.default.svc.cluster.local
    babudb.repl.participant.0.port = 35678
    babudb.repl.participant.1 = xtreemfs-dir-1.xtreemfs-dir.default.svc.cluster.local
    babudb.repl.participant.1.port = 35678
    babudb.repl.participant.2 = xtreemfs-dir-2.xtreemfs-dir.default.svc.cluster.local
    babudb.repl.participant.2.port = 35678
    babudb.repl.sync.n = 2
    babudb.repl.backupDir = /var/lib/xtreemfs/server-repl-dir
    plugin.jar = /usr/share/java/babudb-replication-plugin.jar
---
# XtreemFS Dir Service
apiVersion: v1
kind: Service
metadata:
  name: xtreemfs-dir
spec:
  type: NodePort
  ports:
  - name: http-port
    port: 30638
    targetPort: 30638
    nodePort: 30638
  - name: listen-port
    port: 32638
    targetPort: 32638
    nodePort: 32638
  - name: repl-port
    port: 35678
    targetPort: 35638
    nodePort: 35638
  selector:
    app: xtreemfs-dir
---
# XtreemFS Dir StatefulSet
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: xtreemfs-dir
spec:
  replicas: 3  # 可以是1个或更多
  selector:
    matchLabels:
      app: xtreemfs-dir
  serviceName: xtreemfs-dir  # 必须指定service
  template:
    metadata:
      labels:
        app: xtreemfs-dir
    spec:
      initContainers:
        - name: init-xtreemfs-dir
          image: harbor.huoyin.com:5000/amd64/amd64-xtfs-dir:1.6.0
          imagePullPolicy: IfNotPresent
          command:
            - bash
            - "-c"
            - |
              UUID=$(uuidgen)
              mkdir /etc/xos/xtreemfs/server-repl-plugin -p
              cp -f /mnt/dirconfig.properties /etc/xos/xtreemfs/dirconfig.properties
              cp -f /mnt/dir.properties /etc/xos/xtreemfs/server-repl-plugin/dir.properties
              chown -R root:xtreemfs /etc/xos/xtreemfs/*
              echo "uuid = ${UUID}" >> /etc/xos/xtreemfs/dirconfig.properties
          volumeMounts:
            - name: xtreemfs-dir-conf
              mountPath: /etc/xos/xtreemfs/
            - name: config-map
              mountPath: /mnt/
      containers:
        - name: xtreemfs-dir
          image: harbor.huoyin.com:5000/amd64/amd64-xtfs-dir:1.6.0
          imagePullPolicy: IfNotPresent
          ports:
            - name: http-port
              containerPort: 30638
            - name: listen-port
              containerPort: 32638
            - name: repl-port
              containerPort: 35678
          startupProbe:
            tcpSocket:
              port: 30638
            failureThreshold: 30
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 30638
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
          volumeMounts:
            - name: xtreemfs-dir-conf
              mountPath: /etc/xos/xtreemfs/
  #          - name: xtreemfs-dir-database
  #            mountPath: /var/lib/xtreemfs/dir/database
      volumes:
        - name: xtreemfs-dir-conf
          emptyDir: {}
        - name: config-map
          configMap:
            name: xtreemfs-dir-conf
 #       - name: xtreemfs-dir-database
 #         hostPath:
 #           path: "/var/lib/xtreemfs-dir-database"
